dist: xenial
language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres
  - cd src

script:
  - python manage.py test
